name: Build linux wheel
# Build on every workflow_dispatch, branch push, tag push, and pull request change
on:
  push:
    branches:
      - workfolw_test
  # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build_wheels_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
         CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
         CIBW_SKIP: "cp36-* cp37 *-musllinux_* pp* *-*linux_{aarch64,ppc64le}"
         #CIBW_SKIP: "cp36-* cp37-* *-manylinux2014* *-musllinux_* pp* *-*linux_{aarch64,ppc64le}"
         CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
          auditwheel repair
          --exclude libdb2.so.1
          --exclude libDB2xml4c.so.58
          --exclude libm.so.6
          --exclude libcrypt.so.1
          --exclude libpam.so.0
          --exclude librt.so.1
          --exclude libpthread.so.0
          --exclude libc.so.6
          --exclude libdl.so.2
          --wheel-dir {dest_dir}
          {wheel}
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: ibmdb-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
