name: Build linux wheel
# Build on every workflow_dispatch, branch push, tag push, and pull request change
on:
  push:
    branches:
      - workfolw_test
  # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build_wheels_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
         CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64
         CIBW_SKIP: "cp36-* cp37-* *-musllinux_* pp* *-*linux_{aarch64,ppc64le}"
         CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: ibmdb-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
