name: Build Wheel with cibuildwheel

on: 
  push:
    branches: [workflow_test]

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheel
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: auto

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-wheel
          path: wheelhouse/*.whl
